version: '3'

services:
  app:
    container_name: app_django_quad
    build:
      context: .
      dockerfile: ./src/Dockerfile
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - .env.example
    volumes:
      - ./src/:/usr/src/app/


